# Site settings
encoding: "utf-8"
timezone: Europe/Warsaw
lang: "en-GB"
locale: "en-GB"
languages: ["en", "pl"]
cookie_lang: "hl"
incremental: true

layouts_dir         : _layouts
includes_dir        : _includes

title: "Blokada zdalna"

author:
  name:  "Blokada zdalna"
  url:   https://github.com/blokada-zdalna-pl
  
seo:
  type: "Organization"
  links:
    - https://blokadazdalna.pl/
    - https://github.com/blokada-zdalna-pl/

defaults:
  -   scope:
        path: "./_pages/"
        type: "pages"
      values:
        layout:  "single"

  -   scope:
        path: "./_pages/pl/"
        type: "pages"
      values:
        layout:   "single"
        lang:     "pl-PL"
        locale:   "pl-PL"
        language: "pl"

exclude:
  - ".github/"
  - ".history/"
  - "TODO.md"
  - "README.md"
  - "Makefile"
  - ".jekyll-cache"
  - "LICENSE"
  - "CNAME"
  - "Gemfile"
  - "Gemfile.lock"
  - "/.tmp/"

include:
  - "_pages"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-include-cache
  - jekyll-seo-tag
